name: Validate and Deploy Azure Resources

on:
  push:
    branches:
      - main  # Hier die Haupt-Branch deines Repositories eintragen

jobs:
  validate_and_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Lädt den Repository-Code herunter

# Install packages that are needed for the deployment
    - name: Install Azure PowerShell module
      run: Install-Module -Name Az -Force -AllowClobber

# Connecting to azure
    - name: Login to Azure
      run: |
        $servicePrincipal = @{
          clientId       = "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenantId       = "${{ secrets.AZURE_TENANT_ID }}"
        }
         $credential = New-Object -TypeName PSCredential -ArgumentList $servicePrincipal.clientId, $(ConvertTo-SecureString -String $servicePrincipal.clientSecret -AsPlainText -Force)

          Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $servicePrincipal.tenantId

    - name: Validate Bicep files
      run: az bicep build -f *.bicep --out .  # Validiert die Bicep-Dateien

    - name: Execute PowerShell Script
      shell: pwsh

      az deployment group create --resource-group rg-kevin-kurz --template-file UserStory3.bicep --parameters parameter.production.json

      run: |
        ""