name: Validate and Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  validate_and_deploy:
    runs-on: windows-latest

    # Download repository
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Install packages that are needed for the deployment
    - name: Install Azure PowerShell module
      run: Install-Module -Name Az -Force -AllowClobber

    # Connecting to azure
    - name: Login to Azure
      run: |
        $servicePrincipal = @{
          clientId       = "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenantId       = "${{ secrets.AZURE_TENANT_ID }}"
        }
        $credential = New-Object -TypeName PSCredential -ArgumentList $servicePrincipal.clientId, $(ConvertTo-SecureString -String $servicePrincipal.clientSecret -AsPlainText -Force)

          Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $servicePrincipal.tenantId

    # Validate bicep-data
    - name: Validate Bicep files
      run: |
      az bicep build -f *.bicep --out

    # # Execute powershell script
    # - name: Execute PowerShell Script
    #   #shell: pwsh
    #   run: |
    #     "" 
      # az deployment group create --resource-group rg-kevin-kurz --template-file UserStory3/UserStory3.bicep --parameters UserStory3/parameter.production.json